stages:
- name: Run Tests
  steps:
  - runScriptConfig:
      image: node:alpine
      shellScript: |-
        yarn install
        yarn run test
        yarn run test:publish_coverage
    envFrom:
    - sourceName: leetbot
      sourceKey: CODECOV_TOKEN
      targetKey: CODECOV_TOKEN
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: leetbot:${CICD_EXECUTION_SEQUENCE}
  when:
    branch:
      include:
      - master
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yml
  when:
    branch:
      include:
      - master
