version: '3.1'

services:
  bots:
    build: .
    command: ["yarn", "run", "bot:dev"]
    env_file:
      - .env
    volumes:
      - ./dist:/usr/app/dist

  bots-prod:
    build: .
    env_file:
      - .env
