version: '3.1'

services:
  bots:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    volumes:
      - ./dist:/usr/app/dist

  bots-prod:
    build: .
    env_file:
      - .env
