apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram-bots
  namespace: telegram-bots
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: rook-ceph-block