apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: telegram-bots
  namespace: telegram-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bots
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: telegram-bots
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      restartPolicy: Always
      containers:
      - env:
        - name: LEETBOT_DUMP_FILE
          value: /mnt/dump.json
        - name: LEETBOT_DUMP_CRON
          value: "*/5 * * * *"
        - name: LEETBOT_HOURS
          value: "13"
        - name: LEETBOT_MINUTES
          value: "37"
        - name: LEETBOT_USERNAME
          value: YeetBot
        - name: TIMEZONE
          value: Europe/Berlin
        - name: COMMIT
          value: "${CICD_GIT_COMMIT}"
        envFrom:
        - secretRef:
            name: telegram-bots-env
            optional: false
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        name: telegram-bots
        volumeMounts:
        - mountPath: /mnt
          name: telegram-bots
      volumes:
      - name: telegram-bots
        persistentVolumeClaim:
          claimName: telegram-bots
