apiVersion: apps/v1beta2
kind: Deployment
metadata:
  generation: 1
  name: leetbot
  namespace: telegram-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-telegram-bots-leetbot
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-telegram-bots-leetbot
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      restartPolicy: Always
      containers:
      - env:
        - name: LEETBOT_DUMP_FILE
          value: /mnt/dump.json
        - name: LEETBOT_DUMP_CRON
          value: "*/5 * * * *"
        - name: LEETBOT_HOURS
          value: "13"
        - name: LEETBOT_MINUTES
          value: "37"
        - name: LEETBOT_USERNAME
          value: YeetBot
        - name: TIMEZONE
          value: Europe/Berlin
        - name: COMMIT
          value: "${CICD_GIT_COMMIT}"
        - name: VERSION
          value: "${CICD_GIT_TAG}"
        envFrom:
        - secretRef:
            name: leetbot
            optional: false
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        name: leetbot
        volumeMounts:
        - mountPath: /mnt
          name: leetbot
      volumes:
      - name: leetbot
        persistentVolumeClaim:
          claimName: leetbot
